version: '3'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: 'FSTR_DB'
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
      POSTGRES_DB: ${DB_NAME:-FSTR}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"


  web:
    build: .
    restart: unless-stopped
    container_name: 'FSTR_API'
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres:
