"""create tables

Revision ID: 9626597b3793
Revises:
Create Date: 2023-10-05 10:21:57.798351
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9626597b3793'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'coords',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.Column('height', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_coords_id'), 'coords', ['id'], unique=False)
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('hashed_password', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('first_name', sa.String(), nullable=True),
        sa.Column('last_name', sa.String(), nullable=True),
        sa.Column('middle_name', sa.String(), nullable=True),
        sa.Column('phone', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table(
        'passages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('beauty_title', sa.String(), nullable=True),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('other_titles', sa.String(), nullable=True),
        sa.Column('connect', sa.String(), nullable=True),
        sa.Column('add_time', sa.DateTime(), nullable=True),
        sa.Column('coords_id', sa.Integer(), nullable=True),
        sa.Column('level_winter', sa.String(), nullable=True),
        sa.Column('level_summer', sa.String(), nullable=True),
        sa.Column('level_autumn', sa.String(), nullable=True),
        sa.Column('level_spring', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['coords_id'],
            ['coords.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_passages_id'), 'passages', ['id'], unique=False)
    op.create_table(
        'images',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('filepath', sa.String(), nullable=True),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('passage_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['passage_id'],
            ['passages.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_passages_id'), table_name='passages')
    op.drop_table('passages')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_coords_id'), table_name='coords')
    op.drop_table('coords')
    # ### end Alembic commands ###
